// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtHLe6QPLYEmI5uIuB2jSsanQZ7yOO3gw',
    appId: '1:1209064995:web:5f7be4dd641116a8e79b96',
    messagingSenderId: '1209064995',
    projectId: 'vshop-e33ff',
    authDomain: 'vshop-e33ff.firebaseapp.com',
    storageBucket: 'vshop-e33ff.appspot.com',
    measurementId: 'G-LKBJ3LW1Q8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAib10myhaIaMopMd_pQBhMAR42YxXT8Fg',
    appId: '1:1209064995:android:dcfad353ce10c6fae79b96',
    messagingSenderId: '1209064995',
    projectId: 'vshop-e33ff',
    storageBucket: 'vshop-e33ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVA4RQLtCUm60pQOoSpgN40ANTbK9Fi98',
    appId: '1:1209064995:ios:8fcefa634047a48be79b96',
    messagingSenderId: '1209064995',
    projectId: 'vshop-e33ff',
    storageBucket: 'vshop-e33ff.appspot.com',
    iosClientId: '1209064995-s541q87pc0lnhcq2vt4lvkk3af6r3jjh.apps.googleusercontent.com',
    iosBundleId: 'com.davidamzou.vshop',
  );
}
